version: "3"
services:
  app1:
    build: ./app1
    ports:
      - "5001:5000"
  app2:
    build: ./app2
    ports:
      - "5002:5000"
  app3:
    build: ./app3
    ports:
      - "5003:5000"
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - demo_db:/var/lib/mysql
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
volumes:
  demo_db:
